"""Property test for the Redactor (task 2.5, design Property 24).

Every Credential here is random and generated by Hypothesis in a realistic shape; none is
a real value. The leak oracle is independent of the Redactor: a plain substring search
for every ``REDACT_MIN_FRAGMENT``-character window of the text inside each Credential.
"""

import re
import string
from dataclasses import dataclass
from typing import Final

from hypothesis import event, given, settings
from hypothesis import strategies as st

from friday.constants import REDACT_MIN_FRAGMENT
from friday.redact import Redactor

K: Final = REDACT_MIN_FRAGMENT

_UPPER_ALNUM: Final = string.ascii_uppercase + string.digits
_BASE64: Final = string.ascii_letters + string.digits + "+/"
_HEX: Final = string.digits + "abcdef"

# The Redactor also masks these secret shapes as defense in depth, so text containing
# one is not expected to come back unchanged even without a Credential fragment.
_KEY_ID_SHAPE: Final = re.compile(r"(?:AKIA|ASIA)[A-Z0-9]{16}")
_API_KEY_PARAM: Final = re.compile(r"api_key=[^&\s\"'#<>]", re.IGNORECASE)


@dataclass(frozen=True)
class SecretText:
    """A set of Credentials and a text that may embed them, whole or in part."""

    secrets: tuple[str, ...]
    text: str


def _fixed(alphabet: str, size: int) -> st.SearchStrategy[str]:
    return st.text(alphabet=alphabet, min_size=size, max_size=size)


@st.composite
def credentials(draw: st.DrawFn) -> tuple[str, ...]:
    """AWS key ID (20), AWS secret (40), optional session token (long), FRED key (32)."""
    key_id = draw(st.sampled_from(["AKIA", "ASIA"])) + draw(_fixed(_UPPER_ALNUM, 16))
    secret = draw(_fixed(_BASE64, 40))
    fred_key = draw(_fixed(_HEX, 32))
    if draw(st.booleans()):
        token = draw(st.text(alphabet=_BASE64, min_size=100, max_size=600)) + "=="
        return (key_id, secret, token, fred_key)
    return (key_id, secret, fred_key)


@st.composite
def _piece(draw: st.DrawFn, secrets: tuple[str, ...]) -> str:
    """Filler text, a whole Credential, a fragment of >= K chars, or a short near-miss."""
    kind = draw(st.sampled_from(["filler", "whole", "fragment", "near_miss"]))
    if kind == "filler":
        return draw(st.text(max_size=40))
    secret = draw(st.sampled_from(secrets))
    if kind == "whole":
        return secret
    if kind == "fragment":
        size = draw(st.integers(min_value=K, max_value=len(secret)))
    else:
        size = draw(st.integers(min_value=1, max_value=K - 1))
    start = draw(st.integers(min_value=0, max_value=len(secret) - size))
    return secret[start : start + size]


@st.composite
def secret_texts(draw: st.DrawFn) -> SecretText:
    """Random Credentials and a text mixing arbitrary filler with whole or partial copies."""
    secrets = draw(credentials())
    pieces = draw(st.lists(_piece(secrets), max_size=12))
    return SecretText(secrets=secrets, text="".join(pieces))


def leaks(text: str, secrets: tuple[str, ...]) -> list[str]:
    """Every K-character window of ``text`` that occurs inside some Credential."""
    windows = (text[i : i + K] for i in range(len(text) - K + 1))
    return [w for w in windows if any(w in s for s in secrets)]


def has_secret_shape(text: str) -> bool:
    """Whether ``text`` holds an AWS key-ID shape or an ``api_key=`` value."""
    return bool(_KEY_ID_SHAPE.search(text) or _API_KEY_PARAM.search(text))


@settings(max_examples=300, deadline=None)
@given(secret_texts())
def test_redaction_removes_credentials_in_full_and_in_part(case: SecretText) -> None:
    """Feature: friday-voice-data-assistant, Property 24: Redaction removes credentials in
    full and in part.

    For any set of Credentials and any text embedding whole Credentials or fragments of 8 or
    more characters at any positions with surrounding text, ``redact`` leaves no substring
    of 8 or more characters of any Credential. Text with no such fragment (and no secret
    shape) is returned unchanged.

    **Validates: Requirements 5.13, 12.4**
    """
    out = Redactor(case.secrets).redact(case.text)

    assert leaks(out, case.secrets) == []
    if not leaks(case.text, case.secrets) and not has_secret_shape(case.text):
        event("no credential fragment: text must be unchanged")
        assert out == case.text
